stages:
    - lint
    - build
    - test

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

lint:
  stage: lint
  image: python:3.12
  before_script:
    - pip install poetry
    - poetry install --no-root --no-interaction --with dev
    - poetry run pre-commit install
  script:
    - poetry run pre-commit

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t ml-app .

test:
  stage: test
  image: python:3.12
  services:
    - name: mongo:7.0.4
      alias: mongo
  variables:
    MONGO_URI: mongodb://mongo:27017
  before_script:
    - pip install poetry
    - poetry install --no-root --no-interaction --with dev
  script:
    - poetry run pytest --disable-warnings
